### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by lifeidle** [liantian-cn/liantian.me#1]
您好，我下载了程序并简单修改了一下app.yaml和settings.py，但是无论是本地还是上传gae后，都是500 Server Error。
请问能否告知具体的安装步骤？
非常感谢！

**Comment by lifeidle** [comment]
对了，后来我又自己瞎折腾，在跟目录下建立了lib目录，并运行了 pip wheel -r ../requirements.txt 。
不过依然无论是在本地还是上传gae后，都是500 Server Error。

**Comment by liantian-cn** [comment]
@lifeidle 抱歉，之前没注意.gitignore默认忽略lib目录，已经更新了

**Comment by lifeidle** [comment]
谢谢！
